AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Buildkite On-Demand

Transform:
- AWS::Serverless-2016-10-31

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Buildkite
        Parameters:
          - BuildkiteAgentToken
          - BuildkiteQueue
      -
        Label:
          default: AWS
        Parameters:
          - EventBridgeBusName
          - VpcSubnetIds
    ParameterLabels:
      VpcSubnetIds:
        default: "(Optional) Which VPC subnets should agent containers run in?"

Parameters:
  EventBridgeBusName:
    Type: String
    Description: Name of an EventBridge Bus in this region that receives Buildkite Partner Events, see https://buildkite.com/docs/integrations/amazon-eventbridge.
    AllowedPattern: ^[a-zA-Z0-9\-\._/]+
  BuildkiteQueue:
    Type: String
    Description: Queue name that agents will be scheduled for on-demand, targeted in pipeline steps using an agent query rule "queue={value}".
    AllowedPattern: ^[a-zA-Z0-9\-_]{1,255}
  BuildkiteAgentToken:
    Type: String
    Description: Buildkite agent registration token, see https://buildkite.com/docs/agent/v3/tokens.
    NoEcho: true
  VpcSubnetIds:
    Type: CommaDelimitedList
    Default: ''
    Description: Comma separated list of VPC subnets to launch agent containers in. If left blank a simple VPC with public subnets, suitable for most use cases, will be created.

Conditions:
  CreateVpc: !Equals [ !Join [ ',', !Ref VpcSubnetIds ], '' ]

Resources:
  Vpc:
    Type: AWS::CloudFormation::Stack
    Condition: CreateVpc
    Properties:
      TemplateURL: vpc.yml

  EcsCluster:
    Type: AWS::ECS::Cluster

  BuildkiteAgentTokenParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /buildkite/agent-token
      Type: String
      Value: !Ref BuildkiteAgentToken

  Scheduler:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:832577133680:applications/buildkite-on-demand-scheduler
        SemanticVersion: '0.1.2'
      Parameters:
        BuildkiteAgentTokenParameterPath: !Ref BuildkiteAgentTokenParameter
        BuildkiteQueue: !Ref BuildkiteQueue
        EventBridgeBusName: !Ref EventBridgeBusName
        VpcSubnetIds: !If [ CreateVpc, !GetAtt Vpc.Outputs.VpcSubnetIds, !Ref VpcSubnetIds ]
        EcsClusterName: !Ref EcsCluster

  Macro:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:832577133680:applications/buildkite-on-demand-transform
        SemanticVersion: '0.1.1'

  Agents:
    Type: AWS::CloudFormation::Stack
    DependsOn: Macro
    Properties:
      TemplateURL: agents.yml