apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: buildkite
  name: buildkite-on-demand-agent-scheduler-role
rules:
- apiGroups:
  - ""
  # at the HTTP level, the name of the resource for accessing Pod
  # objects is "pods"
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - create
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: buildkite-on-demand-agent-scheduler-role-binding
  namespace: buildkite
subjects:
- kind: User
  name: buildkite-on-demand-agent-scheduler
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: buildkite-on-demand-agent-scheduler-role
  apiGroup: rbac.authorization.k8s.io