AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Buildkite On-Demand EKS Agent Scheduler

Transform:
- AWS::Serverless-2016-10-31

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Buildkite
        Parameters:
          - BuildkiteAgentTokenParameterPath
          - BuildkiteQueue
      -
        Label:
          default: AWS
        Parameters:
          - EventBridgeBusName
      -
        Label:
          default: Kubernetes
        Parameters:
          - KubernetesApiServerEndpoint
          - KubernetesNamespace

Parameters:
  EventBridgeBusName:
    Type: String
    Description: Name of an EventBridge Bus in this region that receives Buildkite Partner Events, see https://buildkite.com/docs/integrations/amazon-eventbridge.
    AllowedPattern: ^[a-zA-Z0-9\-\._/]+
  BuildkiteQueue:
    Type: String
    Description: Queue name that agents will be scheduled for on-demand, targeted in pipeline steps using an agent query rule "queue={value}".
    AllowedPattern: ^[a-zA-Z0-9\-_]{1,50}
  BuildkiteAgentTokenParameterPath:
    Type: AWS::SSM::Parameter::Name
    Description: Buildkite Agent registration token parameter path, can be a String or SecureString.
    Default: /buildkite/agent-token
  KubernetesNamespace:
    Type: String
    Default: buildkite
    Description: The kubernetes namespace to schedule jobs in.
  KubernetesApiServerEndpoint:
    Type: String
    Description: HTTP endpoint of the kubernetes Cluster to schedule jobs on.

Resources:
  RunTaskQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 300

  BuildkiteJobScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      # Using BuildkiteQueue enforces that only one scheduler per queue is
      # attached to the EventBridge Bus.
      #
      # BuildkiteQueue can be 50, AWS::Events::Rule Name is limited to 64
      Name: !Sub "${BuildkiteQueue}-Queue"
      Description: Enqueue Job Scheduled events on an SQS queue.
      EventBusName: !Ref EventBridgeBusName
      EventPattern:
        account:
          - !Ref 'AWS::AccountId'
        detail-type:
          - "Job Scheduled"
        detail:
          job:
            agent_query_rules:
              - !Sub "queue=${BuildkiteQueue}"
      Targets:
        - Id: Queue
          Arn: !GetAtt RunTaskQueue.Arn
          InputPath: $.detail
  
  RunTaskQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref RunTaskQueue
      PolicyDocument:
        Version: "2012-10-17"
        Id:
          !Sub
            - "${Queue}/SQSDefaultPolicy"
            - Queue: !GetAtt RunTaskQueue.Arn
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "events.amazonaws.com"
            Action: "sqs:SendMessage"
            Resource: !GetAtt RunTaskQueue.Arn
            Condition:
              ArnEquals:
                "aws:SourceArn": !GetAtt BuildkiteJobScheduledRule.Arn

  BuildkiteRunTask:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that dequeues Buildkite Job Scheduled notifications from an SQS queue and schedules a Kubernetes job for them.
      Runtime: nodejs12.x
      Handler: buildkite-run-task.handler
      CodeUri: src/handlers/
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt RunTaskQueue.Arn
            BatchSize: 1
      MemorySize: 128
      Timeout: 105
      Policies:
        - AWSLambdaBasicExecutionRole
        - SQSPollerPolicy:
            QueueName: !GetAtt RunTaskQueue.QueueName
      Environment:
        Variables:
          KUBERNETES_API_SERVER_ENDPOINT: !Ref KubernetesApiServerEndpoint
          KUBERNETES_NAMESPACE: !Ref KubernetesNamespace
          BUILDKITE_AGENT_TOKEN_PARAMETER_PATH: !Ref BuildkiteAgentTokenParameterPath
  RunTaskLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: BuildkiteRunTask
    Properties:
      RetentionInDays: 1
      LogGroupName:
        !Sub
        - '/aws/lambda/${LambdaName}'
        - LambdaName: !Ref BuildkiteRunTask

  BuildkiteEventsLog:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/events/buildkite/${AWS::StackName}
      RetentionInDays: 1

  BuildkiteEventsLogRule:
    Type: AWS::Events::Rule
    Properties:
      # Using BuildkiteQueue enforces that only one scheduler per queue is
      # attached to the EventBridge Bus.
      #
      # BuildkiteQueue can be 50, AWS::Events::Rule Name is limited to 64
      Name: !Sub "${BuildkiteQueue}-Log"
      Description: Log all Buildkite events to a CloudWatch Log Group
      EventBusName: !Ref EventBridgeBusName
      EventPattern:
        account:
          - !Ref 'AWS::AccountId'
      Targets:
        - Id: Log
          Arn: !GetAtt BuildkiteEventsLog.Arn