---
spec:
  containers:
    - name: agent
      image: buildkite/agent:3
      args:
        - start
        - --disconnect-after-job
        - --disconnect-after-idle-timeout=10
      env:
        - name: BUILDKITE_AGENT_TOKEN
          valueFrom:
            secretKeyRef:
              name: buildkite-agent-token
              key: token
  restartPolicy: Never